[package]
name = "scn-decompiler"
version = "0.1.0"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2018"

[dependencies]
emote-psb = {version = "0.5.0", features = ["serde"]}
serde = "1.0.0"
serde_json = "1.0.0"